"""Create actual HTML review artifacts from explicitly synthetic metadata."""

import sys
from dataclasses import replace
from pathlib import Path

import pandas as pd

from neurocvguard import audit_cohort, write_report
from neurocvguard.config import AuditConfig, ColumnMap
from neurocvguard.models import Cohort

root = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "rendered"
rows = []
for person in range(20):
    for visit in range(2):
        rows.append(
            {
                "observation_id": f"SYNTHETIC-o{person}-{visit}",
                "subject_id": f"SYNTHETIC-p{person}",
                "site": "Fictitious clinic A" if person < 10 else "Fictitious clinic B",
                "diagnosis": "class A" if person % 10 < 5 else "class B",
            }
        )
data = pd.DataFrame(rows)
config = AuditConfig(columns=ColumnMap(session=None, phase="phase"))
cohort = Cohort(data, None, config.columns, tuple(data.observation_id))
report = audit_cohort(cohort, config=config)
write_report(report, output_dir=root / "public")
malicious = '<script>alert("synthetic")</script><img src=x onerror="alert(1)">'
report = replace(
    report,
    limitations=(
        "Explicitly synthetic QA fixture generated by render_fixtures.py; "
        "no real participant data.",
        malicious,
    ),
)
write_report(report, output_dir=root / "sensitive", sensitive_details=True)
print("Created synthetic public and explicitly sensitive JSON/HTML/manifest review artifacts.")
